import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service | Gigabox EHR',
  description:
    'Terms of Service for the Gigabox EHR mobile and web application — research and development status, acceptable use, AI-generated content, and limitation of liability.',
};

export default function EHRTermsPage() {
  return (
    <main className="bg-background min-h-screen">
      <Header />
      <div className="pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-sm text-accent uppercase tracking-wider mb-4">
            Gigabox EHR
          </div>
          <h1 className="text-4xl font-bold mb-2 text-foreground">Terms of Service</h1>
          <p className="text-sm text-foreground/60 mb-8">Effective: April 7, 2026</p>

          <div className="prose prose-lg max-w-none text-foreground/80">
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the Gigabox
              EHR mobile application and the related web application at{' '}
              <a
                href="https://praxis.gigabox.ai"
                className="text-accent hover:text-accent/80"
              >
                praxis.gigabox.ai
              </a>{' '}
              (collectively, &ldquo;EHR&rdquo;). By using EHR, you agree to these Terms.
            </p>

            <h2 className="text-foreground">1. Research and Development Product</h2>
            <p>
              Gigabox EHR is currently a research and development product. It is{' '}
              <strong>not</strong> an FDA-cleared medical device, <strong>not</strong> a
              substitute for clinical judgment, and <strong>not</strong> approved for use
              with real protected health information outside of the demonstration profiles
              provided in the App. Any output generated by EHR (including AI-generated SOAP
              notes, prescriptions, lab orders, imaging orders, or referral letters) is
              illustrative only and must not be relied upon for clinical decision-making
              or patient care.
            </p>

            <h2 className="text-foreground">2. Demonstration Data</h2>
            <p>
              The patient records shown in EHR are fictional. They are not associated with
              any real person, living or deceased. Any resemblance to actual persons is
              unintentional and coincidental.
            </p>

            <h2 className="text-foreground">3. Acceptable Use</h2>
            <p>You agree to:</p>
            <ul>
              <li>Use EHR only for evaluation and demonstration purposes</li>
              <li>
                Not enter real protected health information (PHI) about yourself or any
                other person
              </li>
              <li>Not attempt to reverse-engineer, scrape, or disrupt the service</li>
              <li>Not use EHR to make actual clinical decisions or provide patient care</li>
              <li>Not use EHR to violate any applicable law or regulation</li>
            </ul>

            <h2 className="text-foreground">4. Account</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account
              credentials and for all activity that occurs under your account. You must
              immediately notify us at{' '}
              <a
                href="mailto:info@gigabox.ai"
                className="text-accent hover:text-accent/80"
              >
                info@gigabox.ai
              </a>{' '}
              of any unauthorized access. You may delete your account at any time as
              described in our{' '}
              <Link
                href="/apps/ehr/privacy"
                className="text-accent hover:text-accent/80"
              >
                Privacy Policy
              </Link>
              .
            </p>

            <h2 className="text-foreground">5. Intellectual Property</h2>
            <p>
              The EHR application, design, and content are owned by Gigabox. You receive a
              limited, non-exclusive, non-transferable, revocable license to use the App
              for evaluation and demonstration. You may not copy, modify, distribute,
              sublicense, or create derivative works.
            </p>

            <h2 className="text-foreground">6. AI-Generated Content</h2>
            <p>
              EHR uses third-party large language models to generate visit summaries,
              prescription suggestions, lab order suggestions, referral letters, and other
              clinical-looking text. These outputs are illustrative only and may contain
              factual errors, omissions, or hallucinations. <strong>Do not rely on AI
              output from EHR for any real medical purpose.</strong>
            </p>

            <h2 className="text-foreground">7. Disclaimer of Warranties</h2>
            <p>
              EHR is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
              warranty of any kind. Gigabox disclaims all warranties, express or implied,
              including without limitation merchantability, fitness for a particular
              purpose, non-infringement, accuracy, and uninterrupted operation. We do not
              warrant that EHR will meet your requirements or that any defects will be
              corrected.
            </p>

            <h2 className="text-foreground">8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Gigabox shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages — including
              loss of profits, data, or use — arising from your use of EHR, even if we
              have been advised of the possibility of such damages. Our total liability for
              any claim arising out of or related to EHR shall not exceed one hundred
              United States dollars ($100).
            </p>

            <h2 className="text-foreground">9. Termination</h2>
            <p>
              We may suspend or terminate your access to EHR at any time, with or without
              notice, for any reason. Upon termination, your right to use EHR will cease
              immediately. Sections 5 through 11 of these Terms will survive termination.
            </p>

            <h2 className="text-foreground">10. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. The &ldquo;Effective&rdquo;
              date at the top of this page reflects the most recent change. Continued use
              of EHR after changes constitutes your acceptance of the updated Terms.
            </p>

            <h2 className="text-foreground">11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, United States,
              without regard to conflict of laws principles.
            </p>

            <h2 className="text-foreground">12. Contact</h2>
            <p>
              For questions about these Terms, contact{' '}
              <a
                href="mailto:info@gigabox.ai"
                className="text-accent hover:text-accent/80"
              >
                info@gigabox.ai
              </a>
              .
            </p>

            <hr className="my-8 border-foreground/10" />
            <p className="text-sm text-foreground/60">
              See also:{' '}
              <Link href="/apps/ehr/privacy" className="text-accent hover:text-accent/80">
                Privacy Policy
              </Link>{' '}
              ·{' '}
              <Link href="/apps/ehr/support" className="text-accent hover:text-accent/80">
                Support
              </Link>{' '}
              ·{' '}
              <Link href="/apps/ehr" className="text-accent hover:text-accent/80">
                EHR home
              </Link>
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
}
